name: Publish

on:
  workflow_run:
    workflows: ['Build']
    types:
      - completed

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: npm/@swagit

      - name: Publish packages
        run: |
          cd npm
          set -e
          for dir in @swagit/*; do
            if [ -d "$dir" ]; then
              echo "Publishing $dir"
              cd "$dir"
              npm publish --access public || exit 1
              cd ../..
            fi
          done
          npm publish || exit 1
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
