name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Setup Git
        run: |
          git config --global user.name "Test User"
          git config --global user.email "test@example.com"

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose
